### ISSUE TITLE
DOMException: The requested file could not be read, typically due to permission problems that have occurred after a reference to a file was acquired

### ISSUE THREAD

**Issue by yuwei336** [kdrag0n/fastboot.js#14]
When I flash a zip file, if read smaill file, it will be ok. but if read big file just like product.img(522MB) it will throw: "
ui.js:107 Uncaught (in promise) DOMException: The requested file could not be read, typically due to permission problems that have occurred after a reference to a file was acquired.
flashSelectedFactoryZip @ ui.js:107
async function (async)
flashSelectedFactoryZip @ ui.js:105"

I think it's not permission related issues.

**Comment by kdrag0n** [comment]
Yes, it's not a permission issue. This is the error message shown by android-webinstall for that exception:

> <p>
>     There isn’t enough storage space available to download
>     and unpack the OS. You need at least 5 GB free.
> </p>
> <p>
>     If you’re not low on storage, this is caused by
>     using an incognito window or guest browser profile. These profiles have very low storage limits, so
>     installing from them isn’t possible.
> </p>
> <p>
>     To fix this,
>     <strong>switch to a normal browser profile</strong>
>     and try again.
> </p>

**Comment by davigamer987** [comment]
I'm also having this issue, I'm using kiwi browser so I can access debug console, I'm on a normal profile and I can't flash anything larger than 2gb, any way to get around this ?

**Comment by kdrag0n** [comment]
> I'm also having this issue, I'm using kiwi browser so I can access debug console, I'm on a normal profile and I can't flash anything larger than 2gb, any way to get around this ?

Memory usage is a known issue with no easy fix. #27
