### ISSUE TITLE
NPM Package does not get the latest changes

### ISSUE THREAD

**Issue by ehte92** [kdrag0n/fastboot.js#30]
Hello.

I have been trying to update my project which uses the android-fastboot npm package to flash the Pixel 7 and 7 Pro devices.
I have been seen the fastboot.js repo that there are updates specifically for these devices but they were done after the 1.1.1 version update. And I can also see that the latest version available for android-fastboot is 1.1.1 on both npm and on yarn.

Is this correct or do the packages need to be updated or am I doing something wrong?
Can anyone please advise?

Thanks

**Comment by kdrag0n** [comment]
Published as v1.1.3 because I accidentally published 1.1.2 with outdated code.

**Comment by shaikrilwan** [comment]
@kdrag0n great
